# k8s/secretproviderclass-grafana.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-kv
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a750ced8-c3c6-4f51-a83c-7af9ac41aefa"
    keyvaultName: abhidemo-kv
    cloudName: ""
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
    tenantId: ae9f4a74-b03c-4e45-915f-d4a43471afac
  secretObjects:
  - secretName: grafana-admin-secret
    type: Opaque
    data:
    - objectName: grafana-admin-password
      key: admin-password